name: "Retrieve Application Metadata"
description: "Retrieves application metadata from an API and outputs JFrog Artifactory attributes."
author: "Your Name marcelol@jfrog.com"
inputs:
  application_key:
    description: "The Application Key for API authentication."
    required: true
  ams_token:
    description: "The AMS token for API authentication."
    required: true
  ams_endpoint:
    description: "The AMS endpoint URL. JSON Retuned is expected."
    required: true
runs:
  using: "composite"
  steps:
    - name: Run metadata retrieval script
      shell: bash
      run: |
        ls -ltra
        ./entrypoint.sh ${{ inputs.application_key }} ${{ inputs.ams_token }} ${{ inputs.ams_endpoint }}
