name: "Retrieve Application Metadata"
description: "Retrieves application metadata from an API and outputs JFrog Artifactory attributes."
author: "Your Name marcelol@jfrog.com"
inputs:
  application_key:
    description: "The Application Key for API authentication."
    required: true
  ams_token:
    description: "The AMS token for API authentication."
    required: true
  ams_endpoint:
    description: "The AMS endpoint URL. JSON Retuned is expected."
    required: true
outputs:
  metadata:
    description: "The retrieved application metadata."
    value: ${{ steps.run_metadata_retrieval_script.outputs.stdout }}
  repo_list:
    description: "The list of repositories retrieved."
    value: ${{ steps.run_metadata_retrieval_script.outputs.repo_list }}

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      id: set_github_path
      run: |
        echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
        echo "action_path=$GITHUB_ACTION_PATH" >> $GITHUB_OUTPUT
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    # - name: Check out repository
    #   uses: actions/checkout@v4

    - name: Run metadata retrieval script
      id: run_metadata_retrieval_script
      shell: bash
      run: |
        entrypoint.sh ${{ inputs.application_key }} ${{ inputs.ams_token }} ${{ inputs.ams_endpoint }}
      env:
        GITHUB_ACTION_PATH: ${{ steps.set_github_path.outputs.action_path }}
