name: "Retrieve Application Metadata"
description: "Retrieves application metadata from an API and outputs JFrog Artifactory attributes."
author: "Your Name <your.email@example.com>"
inputs:
  application_id:
    description: "The Application ID for API authentication."
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entry.sh
      shell: bash
