name: "Retrieve Application Metadata"
description: "Retrieves application metadata from an API and outputs JFrog Artifactory attributes."
author: "Your Name <your.email@example.com>"
inputs:
  application_id:
    description: "The Application ID for API authentication."
    required: true
outputs:
  repo_list:
    description: "A List"
    value: ${{ steps.get_app.outputs.repo_list }}
  docker-repo:
    description: "Pussh to repo"
    value: ${{ steps.get_app.outputs.docker-repo }}
  python-remote-repo:
    description: "Pypi Proxy"
    value: ${{ steps.get_app.outputs.python-remote }}
runs:
  using: "composite"
  steps:
    - name: Mine
      id: get_app
      run: |
       chmod 750 ${{ github.action_path }}/entry.sh
       bash -c ${{ github.action_path }}/entry.sh
      shell: bash
